version: '3'
services: 
  app:
    build: 
      dockerfile: Dockerfile
      context: ./server
    ports: 
      - "8000:8000"
    volumes:
      - ./server/app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"