# Generated by Django 2.2.14 on 2020-07-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=1.0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
