# Generated by Django 2.2.14 on 2020-07-23 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecurrency',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseCurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
