# Generated by Django 2.2.14 on 2020-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200723_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecurrency',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
