apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: bblaise/currency-converter-server
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: currency_converter
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
